# Generated by Django 4.2.7 on 2023-11-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alumno_delete_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('idConductor', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Conductor')),
                ('Gmail', models.CharField(max_length=50, verbose_name='Gmail')),
                ('Contrasena', models.CharField(max_length=50, verbose_name='Contrasena')),
                ('nombreConductor', models.CharField(max_length=50, verbose_name='Nombre de Conductor')),
            ],
        ),
    ]
