# Generated by Django 4.1.5 on 2023-11-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_conductor_automarca_conductor_autopatente'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='vPersona',
            field=models.IntegerField(default=0, verbose_name='Valor por Persona'),
            preserve_default=False,
        ),
    ]
