# Generated by Django 4.1.6 on 2023-11-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_conductor_vpersona'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='horaSalida',
            field=models.TimeField(default=None, null=True, verbose_name='Hora Salida'),
        ),
    ]
